"""initial schema

Revision ID: 5d5e4deb843b
Revises: 
Create Date: 2026-04-15 00:37:22.569638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5e4deb843b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('threshold', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_index('ix_alerts_symbol_time', 'alert_events', ['symbol', 'timestamp', 'severity'], unique=False)
    op.create_table('analysis_result_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('baseline_snapshot_id', sa.Text(), nullable=False),
    sa.Column('scores_json', sa.Text(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('scenario_confidence', sa.Float(), nullable=False),
    sa.Column('strategies_json', sa.Text(), nullable=False),
    sa.Column('meso_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_index('ix_ars_symbol_time', 'analysis_result_snapshots', ['symbol', 'created_at'], unique=False)
    op.create_table('market_parameter_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id')
    )
    op.create_index('ix_mps_symbol_time', 'market_parameter_snapshots', ['symbol', 'captured_at'], unique=False)
    op.create_table('monitor_state_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monitor_id', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('analysis_id', sa.Text(), nullable=False),
    sa.Column('baseline_snapshot_id', sa.Text(), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_id')
    )
    op.create_index('ix_mss_symbol_time', 'monitor_state_snapshots', ['symbol', 'captured_at'], unique=False)
    op.create_table('tracked_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('analysis_id', sa.Text(), nullable=False),
    sa.Column('strategy_index', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('legs_json', sa.Text(), nullable=False),
    sa.Column('entry_spot', sa.Float(), nullable=False),
    sa.Column('entry_iv', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id')
    )
    op.create_index('ix_positions_symbol', 'tracked_positions', ['symbol', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_positions_symbol', table_name='tracked_positions')
    op.drop_table('tracked_positions')
    op.drop_index('ix_mss_symbol_time', table_name='monitor_state_snapshots')
    op.drop_table('monitor_state_snapshots')
    op.drop_index('ix_mps_symbol_time', table_name='market_parameter_snapshots')
    op.drop_table('market_parameter_snapshots')
    op.drop_index('ix_ars_symbol_time', table_name='analysis_result_snapshots')
    op.drop_table('analysis_result_snapshots')
    op.drop_index('ix_alerts_symbol_time', table_name='alert_events')
    op.drop_table('alert_events')
    # ### end Alembic commands ###
